//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsEentityFramework.BusinessLogicClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public Comments()
        {
            this.Comments1 = new HashSet<Comments>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int CommentID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Text { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime Date { get; set; }
        public bool C_Confirm { get; set; }
        public bool C_Read { get; set; }
        public int C_Like { get; set; }
        public int C_DisLike { get; set; }
    
        public virtual ICollection<Comments> Comments1 { get; set; }
        public virtual Comments Comments2 { get; set; }
        public virtual Products Products { get; set; }
    }
}
