//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsEentityFramework.BusinessLogicClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guaranty
    {
        public Guaranty()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Descreption { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
