//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsEentityFramework.BusinessLogicClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public int Count { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public int PostID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users1 Users { get; set; }
    }
}
