//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsEentityFramework.BusinessLogicClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pics
    {
        public Pics()
        {
            this.Pic_Products = new HashSet<Pic_Products>();
        }
    
        public int ID { get; set; }
        public string PicName { get; set; }
    
        public virtual ICollection<Pic_Products> Pic_Products { get; set; }
    }
}
